### ISSUE TITLE
Annotation and interface can't be imported at the same time.

### ISSUE THREAD

**Issue by ScottPierce** [mg6maciej/hrisey#2]
Here is one of the example codes you provide:

``` java
@hrisey.Parcelable
class ParcelableClass implements android.os.Parcelable {

    String myString;
}
```

Could you make it so that android.os.Parcelable doesn't have to be implemented on the class, and that part will be generated, or could you change it so that the annoation has a different name (like @Parcel) so that both can be imported at the same time?

**Comment by mg6maciej** [comment]
`android.os.Parcelable` doesn't have to be declared as being implemented. It is only there for convenience. Without it, IDE will highlight it not being `Parcelable` when you use it in Bundle, Intent's extras, etc. Nothing I can do about it before an issue pointed out by Roman [here](https://devnet.jetbrains.com/message/5515061) is resolved. The code will still compile without `implements`.
I'd rather not change the name as it is public API. Currently if you only use the class in `onSaveInstanceState` and use `@hrisey.InstanceState`, you won't see false red highlights. When I add `@Extra` and `@Argument`, there will be even less reasons to directly work with such parcelables and defining them as implementing `android.os.Parcelable`.
