### ISSUE TITLE
Not generating classes correctly.

### ISSUE THREAD

**Issue by ScottPierce** [mg6maciej/hrisey#3]
I've tried switching from Lombok to hrisey for the @Parcelable annotation, but I'm having weird issues. It doesn't actually seem to be generating anything.

``` Error
Error:(127, 62) Gradle: error: constructor Age in class Age cannot be applied to given types;
required: no arguments
found: Integer,int
reason: actual and formal argument lists differ in length
```

`Error:(138, 17) Gradle: error: cannot find symbol method getCalculatedAge()`

And there are several other errors that come up after that. It seems that nothing is being generated.

`provided 'pl.mg6.hrisey:hrisey:0.3.+'`

``` Java
@RequiredArgsConstructor(suppressConstructorProperties = true)
@Parcelable @Value public class Age implements android.os.Parcelable {

  @SerializedName("calculatedAge")
  Integer calculatedAge;

  @SerializedName("userAge")
  int userAge;

  public Integer getNetAge() {
    if (calculatedAge == null)
      return null;
    else
      return calculatedAge - userAge;
  }

}
```

I was using JDK 8, but switched to JDK 7 and got the same issue.

I'm using `classpath 'com.android.tools.build:gradle:0.13.+'` as well.

Any recommendations?

**Comment by mg6maciej** [comment]
I have tried to compile this class with JDK 7 and had no problems. On JDK 8 I had an error like in #1. So this probably means some other preprocessing lib/tool grabs the code before Lombok does.  
Did it work before adding `@Parcelable`? Could you remove `@Parcelable` and implement it by hand (or better yet generate parcelable code with parcelable intellij plugin)?  
What JSR 269 (Plugabble Annotation Processing API) based libraries do you use? Especially in the code that tries to call `Age` constructor and getter. Can you paste dependencies from build.gradle?  
All questions aside, it would be best to have failing code somewhere, so I can see the error myself. I added your class to [hrisey-error/age branch in a demo app](https://github.com/mg6maciej/simple-github-client/tree/hrisey-error/age), so you may base on this or create another simple repo with as little deps as possible.

**Comment by ScottPierce** [comment]
I use dagger and butterknife, but both don't really interact with the class.

I don't want to implement Parcelable code by hand, and there are limitations I believe on the Parcelable intellij plugin, that didn't allow me to use it for one of my use cases (Plus I'd really like to avoid IDE vomit).

```
    apt "com.squareup.dagger:dagger-compiler:1.2.2"
    apt 'com.jakewharton:butterknife:5.1.2'
    provided 'pl.mg6.hrisey:hrisey:0.3.+'
    compile 'com.squareup.picasso:picasso:2.3.4'
    compile 'com.google.android.gms:play-services:6.1.+'
    compile 'com.android.support:appcompat-v7:21.0.+'
    compile 'com.android.support:cardview-v7:21.0.+'
    compile 'com.android.support:recyclerview-v7:21.0.+'
    compile 'de.greenrobot:eventbus:2.2.1'
    compile 'de.greenrobot:greendao:1.3.7'
    compile "com.netflix.rxjava:rxjava-android:${RXJAVA_VERSION}"
```

Everything worked fine with Lombok. I was trying to transition from Lombok to Hrisey.

Here is the calling code that gives me an error first, but there are plenty of places after too.

``` Java
@Synchronized("AgeLock") public Age getAge() {
    int storedCalculatedAge = mSharedPreferences.getInt(KEY_CALCULATED_AGE, -1);
    int userAge = mSharedPreferences.getInt(KEY_USER_AGE, -1);
    Integer calculatedAge = (storedCalculatedAge == -1) ? null : storedCalculatedAge;
    return (calculatedAge == null && userAge == -1) ? null : new Age(calculatedAge, userAge);
  }
```

It fails on the return line for the `new Age`

I'm using the latest IntelliJ13.

I tried removing @Parcelable, and it's still having the same issues.

**Comment by ScottPierce** [comment]
I took a look at the project you setup, and I couldn't get it to build properly. But I did notice that you weren't actually creating and using the object anywhere. Does it still work if you use the object?

**Comment by mg6maciej** [comment]
So simply switching dependency from lombok to hrisey causes build errors? Can you share the whole class where `getAge` is defined if it's not too large?  
Yes, I have copied your `getAge` into an `Activity`, fixed compilation errors and it builds fine.

**Comment by mg6maciej** [comment]
What was the issue building it? Maybe the oldish `compileSdkVersion` or `buildToolsVersion`?

**Comment by ScottPierce** [comment]
To answer why it wasn't building: It was telling me that I couldn't have a non-java module inside an android module. It's not a big deal. I could have fiddled around with it and got it working I imagine. But it did allow me to see that yes you imported the class, but you weren't instantiating it anywhere, which was where my problem was coming in.

<b>So I've fooled around with the problem some more based on your questions and I've got some more data:</b>

``` Gradle
//    provided "org.projectlombok:lombok:1.14.8"
//    apt "org.projectlombok:lombok:1.14.8"
    provided 'pl.mg6.hrisey:hrisey:0.3.+'
```

I'm using the hrisey plugin for both instances.

When I uncomment the lombok dependencies, and comment out the hrisey dependency, it builds fine. But if I switch it back to hrisey, it no longer builds giving me the issues I described above. I've removed @Parcelable. This is what the class is now: 

``` Java
@RequiredArgsConstructor(suppressConstructorProperties = true)
@Value public class Age {

 @SerializedName("calculatedAge")
  Integer calculatedAge;

  @SerializedName("userAge")
  int userAge;

  public Integer getNetAge() {
    if (calculatedAge == null)
      return null;
    else
      return calculatedAge - userAge;
  }

}
```

Again, builds fine with Lombok, but Hrisey seems to be failing to generate things properly on all of my Lombok/Hrisey classes. All Lombok/Hrisey classes are annotated accordingly:

``` Java
@RequiredArgsConstructor(suppressConstructorProperties = true)
@Value
```

I think it's worth noting that I do have static inner classes that are annotated as well. It all works fine with Lombok though.

**Comment by mg6maciej** [comment]
Could you extract a little project that shows the issue? I could not make reproduce it with all the information you have provided already. I feel the most important parts will be `Age` class, file where `@Synchronized("AgeLock") public Age getAge()` method is defined and build.gradle with the same dependencies you have now.

**Comment by ScottPierce** [comment]
Yeah. I'll try and find the time later tonight.

**Comment by ScottPierce** [comment]
When I setup a separate project to duplicate the problem I was able to narrow it down.

Adding an apt line solved the problem:

``` Gradle
provided 'pl.mg6.hrisey:hrisey:0.3.+'
apt 'pl.mg6.hrisey:hrisey:0.3.+'
```

I think previously all I had tried was swapping provided for apt. Anyways, sorry for wasting your time. I'll give the plugin a shot now on my actual project sometime tomorrow and report back.

**Comment by mg6maciej** [comment]
Glad you have found a solution.
Small hint: you can add lombok.config file to your repo [like this one](https://github.com/mg6maciej/VielenGamesAndroidClient/blob/master/lombok.config) instead of annotating each and every file with `@RequiredArgsConstructor(suppressConstructorProperties = true)`.

**Comment by ScottPierce** [comment]
I had no idea. I appreciate that hint :-)

**Comment by ScottPierce** [comment]
Things appear to be working rather wonderfully now. Thank you for your work on this gem of a project. 

The only other issue I had was with a very odd stacktrace from hrisey that gave me no details. I ended up noticing that one of my inner classes wasn't static, and fixed it, and that made the build error go away. 

It's exactly as convenient as I imagined.
